### ISSUE TITLE
gradle 으로 빌드툴을 바꾸는것 검토

### ISSUE THREAD

**Issue by redrebel** [JAVACAFE-STUDY/logjdbc#15]
실제적으로 도움은 많이 못주면서 딴지만 거는것 같아서 미안하지만
Maven 대신에 Gradle 을 빌드툴로 사용하는건 어쩔지 의견드립니다.

**Comment by devsejong** [comment]
제가 gradle을 사용하질 못해서가 가장 이유가 큰 것같네요. 도움을 주셔야 될 것 같아요.

Gradle은 제가 도중에 공부를 그만두었었어요. 이유가 여럿 있었는데.
첫째 문법자유도가 높아, 하나의 역할을 여러 표현으로 처리가 가능하다는 것 때문에, 일관성이 없는 코드가 나오는점. 두번째로 빌드,테스트속도가 메이븐에 비해서 매우 느리다는점. 그리고 버전업에 따라서 코드 호환이 잘 안되는 점.

그럼에도 지금 Gradle이 필요한 시점이 되었네요. 스프링부트 AutoConfig를 작성중인데,  메이븐에서는 동적으로 버전을 변경할 수 없네요. Spring Boot 1.3.5와 1.4.0 동시에 배포하기 위해선 Maven을 사용할 경우 프로젝트 두벌을 작성해야됩니다. 그래들로 이 문제를 풀고싶네요.

**Comment by redrebel** [comment]
#25

**Comment by changhwa** [comment]
@devsejong 
메이븐도 profile을 이용하면 원하시는 기능이 가능합니다.
실제로 예전 프로젝트에서 그루비 3가지 버전으로 배포했던 기억이 있습니다.
필요하시면 한번 찾아볼게요.

**Comment by changhwa** [comment]
@devsejong 

그냥 dependency version 정보에 ${...} property 명을 넣고
profile에서 해당 프로퍼티를 정의해주면 됩니다.
참고하세용

**Comment by devsejong** [comment]
지금 Maven으로 구성된 상태가 크게 복잡하지 않은 상태입니다.
현재 dependency는 총 3개가 걸려있으며, maven으로도 큰 문제없이 설정이 되어있습니다.
해당 라이브러리의 Gradle 변경은 좀더 빌드가 복잡해진다고 한다면 그때 도입하는게 옳을 것 같습니다.

버전이 문제가될 [Spring boot Autocofing](https://github.com/JAVACAFE-STUDY/logjdbc-springboot-autocofing)에서는 그래들을 사용해보도록 하겠습니다.
