### ISSUE TITLE
Maven install 시 console창에서 한글깨짐 현상

### ISSUE THREAD

**Issue by heejunghwang** [JAVACAFE-STUDY/logjdbc#16]
각각의 파일들을 JUnit으로 실행하면 한글이더라도 정상적으로 console창에 잘 나옵니다.
그러나, Maven install 시에 한글일 경우 한글깨짐 현상이 있는데 이클립스에서 설정하는 부분이 따로 있는건가요?(참고로 eclipse에서 Window-Preference-Workspace에서 인코딩은 UTF-8로 설정했고, 프로젝트 설정에서 인코딩 설정도 마찬가지 입니다)
아니면 한글 깨짐 현상이 정상인건가요?
답변 부탁드립니다.
![default](https://cloud.githubusercontent.com/assets/6778562/17296633/3298ab48-583d-11e6-8bde-6b01af7aec02.PNG)

**Comment by devsejong** [comment]
메이븐이 별도로 돌아가기 때문에 UTF-8 설정이 별도로 필요하네요.
수정본 업데이트하였습니다. ㅎㅎ
