### ISSUE TITLE
로그 순서 문의

### ISSUE THREAD

**Issue by heejunghwang** [JAVACAFE-STUDY/logjdbc#19]
LogJdbcDataSourceTest.java 파일을 테스트해보고 있는데, resultSet을 close 시점에 로그를 출력하는 형태인 것 같은데, resultSet을 받아오는 순서대로 로그를 출력하는게 맞는지, resultSet을 close하는 순서대로 로그를 출력하는게 맞는지 답변 부탁드립니다. :)

예1) 
ResultSet resultSet = pstmt.executeQuery();
ResultSet resultSet2 = pstmt.executeQuery();
ResultSet resultSet3 = pstmt.executeQuery();
resultSet.close();  //  - 1
resultSet2.close(); // - 2
resultSet3.close();  // - 3
-> 결과 : 1,2,3 순서로 출력

예2)
ResultSet resultSet = pstmt.executeQuery();
ResultSet resultSet2 = pstmt.executeQuery();
ResultSet resultSet3 = pstmt.executeQuery();
resultSet3.close();  // -3
resultSet.close(); // - 1
resultSet2.close();  // -2
-> 결과 : 3.1,2 순서로 출력

**Comment by devsejong** [comment]
close를 먼저한 순서대로 출력되고 있습니다.
어느 시점에서  로그를 보여주어야 할지는 아직도 계속 고민중이예요. ㅎㅎ

한번에 SQL, Parameter, resultSet을 보여주는게 한눈에 들어온다고 판단했구요.
그래서 제일 마지막 작업이 종료되는 시점에서(close호출) 로그가 출력되도록 해놓았습니다. Exception이 발생하면 그 순간 모아놓았던 로그를 모두 출력하도록 해놓았구요.

좀더 내부적으로 들어가자면 PreparedStatement, 또는 Statement를 호출하는 순간 LoggingCollector를 생성합니다. 설정정보와 관련정보를모을수 인스턴스를 생성합니다. 작업이 진행되면서 이 인스턴스로(XxxxCollector 사용) 로깅정보가 모이게 됩니다.
모인 정보는 close호출될 때 설정정보(LogJdbcConfiguration)을 기준으로 로그의 문자열을 조립하고, 이 로그를 출력(XxxxPringter 사용)하도록 해놓았습니다.

**Comment by devsejong** [comment]
저번에 시도하려고 했던게 이걸 그림으로 그려서 공유하는건데, 계속 늦어지고 있네요. 집에가서 작업 후 공유하도록 할께요.

질문 감사합니다.

**Comment by heejunghwang** [comment]
답변감사합니다~ㅎㅎㅎ SQL, Parameter, resultSet을 한번에 보여주는게 보기 편하고 좋긴하지만, 
예를 들어서 3개의 쿼리중 1번째 쿼리만 느리다고 가정하였을 때, 호출은 1,23번으로 하였지만,
2,3번 로그가 먼저 표시되고 1번이 표시된다면, 호출순서로 보이지 않기 때문에 헷갈릴 것 같습니다.

추가적으로, 개인적인 의견으로는 쿼리 실행 속도(시간)이나 resultSet의 count도 로그에 표시되면 더 좋을 것 같습니다.

**Comment by redrebel** [comment]
이 이슈는 저 역시 논의를 했던 내용입니다. #2 
resultSet을 언제 보여주는것이 효율적인지는 분명 고민을 많이 해야되는 사항같습니다.

사용자는 개발중 혹은 디버깅과정속에서 쿼리내용 및 결과셑의 내용이 궁금해서 확인용도로 사용하는 것으로, 
저는 이 프로젝트를 정의한다고 개인적으로 생각합니다.(물론 개발자분은 다른 생각이실수도...)
결국 실제 서비스중에 사용되는 기능이 아니기 때문에 
사용하는 입장에서 어떤것이 좋게 느껴지느냐의 사용자 관점에서 접근하는 것이 가장 좋은 생각인것 같습니다.
안정성을 제외 하고는 구현의 복잡성이나  효율성, 성능등은 논의에서 잠시 접어두는것도 좋은것 같습니다.
(혹은 설정을 통한 On/Off)

성능 등은 잠시 접어두고 과연 개발하거나 디버깅하는 과정속에서 언제 나는 SQL이나 ResultSet 내용이 궁금할까?
물론 레거시 소스를 건드는것은 자제해야겠죠.
좀 더 고민해보겠습니다.^^

**Comment by devsejong** [comment]
지금 다른 라이브러리를 사용하고 있는데, 여기선 SQL따로 결과 따로 찍히고 있어서 많이 불편했었거든요. 어떤 SQL에 대한 결과가 나온건지가 잘 드러나지 않아서 한번에 찍히는걸 선택한거구요.

저도 좀 더 고민해볼께요. 이게 맞는지는 저도 잘 확신이 잘 안서고 있네요.

저는 이 라이브러리를 운영단계까지 사용하려고 했었어요. 옵션으로 에러시에만 로그가 출력되도록 설정하려고 하고 있구요. #11 

이거 참조 부드려ㅑ요

**Comment by redrebel** [comment]
SQL 관점에서 CRUD 에 대하여 Case By Case 로 생각과 의견교환을 계속 진행해 나가야 될것 같습니다.
(어떻게 구현하느냐는 잠시 제외)

C(create)는 주로 insert를 말하는건데
SQL문이 중요할것 같습니다.

R(read)는 일반적으로 select인데
resultSet이 중요하고 SQL는 보다 적게 중요할 것 같습니다.

U(update)는 그대로 update 인데
SQL문이 중요할것 같습니다.

D(delete)는 글쎄요... 
개발 및 운영중에 소스단에서 데이터를 삭제하는것이 배치성 업무빼고는 적을것 같습니다.

위의 이야기는 너무도 당연한 이야기라서 resultSet 이야기하는데 먼소리야? 하겠지요?

전에도 #5 개발자분이 언급했지만, 
DB 의 특성이 달라서(관계형, 그래프형, 객체형) resultSet 을 직접 control 하기가 애매하다는 것입니다.
아울러 배치성 업무나 많은 데이터를 처리해야되는 경우 모든 레코드를 모두 Collector에 넣고 한번에 logging 하는것도 무리가 있어보입니다.

결국 결론은 이야기하지않고 뜬구름만 날리다가 저는 사라집니다.뽕.~

**Comment by devsejong** [comment]
이렇게 결론이 안날때에는 일단 써보고 결정하는걸로!!!!

나름 잘 나누어놓아서 나누는거야 별일없어요. ㅎㅎㅎ

**Comment by devsejong** [comment]
사용하면서 불편하다고 생각하신다면 재오픈해주세요.
당장은 Close처리하겠습니다.
