### ISSUE TITLE
SQL 문법 오류 로그에 표시가 안되는 현상

### ISSUE THREAD

**Issue by heejunghwang** [JAVACAFE-STUDY/logjdbc#23]
LogJdbcDataSourceTest.java 파일에서 테스트한 현상입니다. (develop branch에서 테스트)

SELECT * FROM CUSTOMERS WHERE  NAME=? AND

이런식으로 SQL 문법 오류를 낼 때, 로그가 전혀 표시가 되지 않는 현상이 있는 것 같습니다.
SQL 문법 오류에 대한 로그 처리 부분 확인이 필요 할 것 같습니다.

참고 소스)
        try(PreparedStatement pstmt3 = connection.prepareStatement("SELECT * FROM CUSTOMERS WHERE  NAME=? AND");){
            pstmt3.setString(1, "Hardik");
            ResultSet resultSet3 = pstmt3.executeQuery();
            while (resultSet3.next()) {
            }
        }catch(Exception e){
        	e.printStackTrace();
        }

**Comment by devsejong** [comment]
확인 감사합니다. 저녁에 수정하도록 할께요.

**Comment by devsejong** [comment]
H2같은 경우에는 실행시점이 아니라 SQL을 설정하는 순간에 에러를 뱉어내고 있네요. 이부분도 try/catch로 묶어주도록 해야겠네요.
